parameters:
#    edge_analytics.example.class: Edge\Bundle\AnalyticsBundle\Example

services:
#    edge_analytics.example:
#        class: %edge_analytics.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
