edge_analytics_analyticsjs:
    pattern:  /analytics/js
    defaults: { _controller: EdgeAnalyticsBundle:Analytics:js }
    requirements:
      _method:  GET
edge_analytics_collect:
    pattern:  /analytics/collect
    defaults: { _controller: EdgeAnalyticsBundle:Analytics:collect }
    requirements:
      _method:  POST